config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :reviews
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  namespace :admin do
    resources :reviews
    resources :users
    resources :categories
  end
  resources :reviews do
    member do
      get 'like', to: "reviews#like"
      get 'unlike', to: "reviews#unlike"
    end
    resources :comments
  end
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root "static_pages#home"
  get '/profile', to: 'static_pages#profile'
  get '/manager_reviews', to: 'static_pages#manager_reviews'
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::AdminController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all.paginate(:page => params[:page],:per_page => 10);
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # # GET /reviews/new
  # def new
  #   @review = Review.new
  # end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  # def create
  #   @review = current_user.reviews.new(review_params)

  #   respond_to do |format|
  #     if @review.save
  #       format.html { redirect_to @review, notice: 'Review was successfully created.' }
  #       format.json { render :show, status: :created, location: @review }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @review.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to admin_reviews_path, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_review
      @review = Review.find(params[:id])
    end
    def review_params
      params.require(:review).permit(:image, :title, :content,:created_at)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :like, :unlike]
   before_action :authenticate_user!, only: [:edit, :update, :destroy, :show]
  before_action :check_owned, only: [:edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    if params[:category_id] != "0" && params[:category_id] != nil
      @category_id = params[:category_id]
      @filters = Review.where(:category_id => @category_id)
    else
      @category_id = 0
      @filters = Review.all
    end
    @filters = @filters.search(params[:search])
    @reviews = @filters.paginate(:page => params[:page],:per_page => 10)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def like
    @review.liked_by current_user
    respond_to do |format|
      format.html { redirect_to @review }
      format.js { render layout: false }
    end
  end
  
  def unlike
    @review.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to @review }
      format.js { render layout: false }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end
    
    def check_owned
      @review = current_user.reviews.find_by_id params[:id]
      if @review.nil?
        respond_to do |format|
          format.html { redirect_to reviews_url, notice: 'You can not edit this review.' }
          format.json { head :no_content }
        end
      end
    end

    def review_params
      params.require(:review).permit(:image, :title, :content,:created_at,:category_id)
    end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/_form.html.erb
<%= form_for [:admin,@review] do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>    
    <%= f.file_field :image,{:onchange => "readURL(this)"} %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :category_id %>
    <%=f.collection_select(:category_id, Category.all, :id, :name, {prompt: true},{:class=>'form-control'})%>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.bootsy_area :content, class: "form-control",rows: 25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', admin_reviews_path %>

app/views/admin/reviews/index.html.erb
<h2>List Review</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Image</th>
        <th>Reviewer</th>
        <th>Action</th>
      </tr>
    </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to review.title,review,:target => '_blank' %></td>
        <td>
            <div class="movie">
				<figure class="movie-poster" style="width:200px;height:auto"><%= image_for_review review.image%></figure>
			</div>
        </td>
        <td>
            <%= link_to review.user.email,admin_user_path(review.user),:target => '_blank' %>
            <%= link_to review.user.name,admin_user_path(review.user),:target => '_blank' %>
            <figure class="movie-poster" style="width:50px;height:auto"><%= avatar review.user.avatar%></figure>
        </td>
        <td><%= link_to "", edit_admin_review_path(review),:class => 'fa fa-edit fa-2x' %><%= link_to '', admin_review_path(review),:class => 'fa fa-trash fa-2x', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @users %>

app/views/admin/reviews/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md-6">
        <figure class="movie-poster"><%=image_tag(@review.image,:class => "detail_image")%></figure>
    </div>
    <div class="col-md-6">
        <h1><%=@review.title%></h1>
        <div class="row">
          <div class="vote_count col-md-1">
            <%= @review.get_likes.size %>
          </div> 
        
          <div class="votes col-md-2">
            <% if current_user.liked? @review %>
              <%= link_to "unlike", unlike_review_path(@review), method: :get, remote: true, class: 'unlike_review btn btn-warning' %>
            <% else %>
              <%= link_to "like", like_review_path(@review), method: :get, remote: true, class: 'like_review btn btn-primary' %>
            <% end %>
          </div>
        </div>
        <%=@review.content.html_safe%>
        <% @review.comments.each do |c| %>
            <p>
                <% if c.user %>
                    <strong><%= c.user.name %> : </strong>
                <% else %>
                    <strong>noname : </strong>
                <% end %>
                
                <%= c.body %>
            </p>
        <% end %>
        <% if current_user %>
            <%= form_for [@review, @comment ||= Comment.new] do |f| %>
                <div class="field">
                    <%= f.text_area :body %>
                </div>
                <div class="actions">
                    <%= f.submit %>
                </div>
            <% end %>
        <% else %>
            <p style="color:red">dang nhap de comment</p>
        <% end %>
        
        
        
        <div class ="update">
            <% if  @review.user == current_user %>
                <%= link_to 'Edit', edit_review_path(@review) %> |
                <%= link_to "Delete",review_path(@review), method: :delete, data: {confirm: t("application.confirm")} %> |
            <% end %>
            <%= link_to 'Back', reviews_path %>
        </div>
    </div>
</div>