config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :reviews
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  namespace :admin do
    resources :reviews
    resources :users
    resources :categories
  end
  resources :reviews do
    member do
      get 'like', to: "reviews#like"
      get 'unlike', to: "reviews#unlike"
    end
    resources :comments
  end
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root "static_pages#home"
  get '/profile', to: 'static_pages#profile'
  get '/manager_reviews', to: 'static_pages#manager_reviews'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BigBug</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <base href="<%=root_url%>">
</head>
<body>
		

		<div id="site-content">
			<header class="site-header">
				<div class="container">
					<a href="" id="branding">
						<img src="logo.png" alt="" class="logo">
						<div class="logo-copy">
							<h1 class="site-title">My   Film</h1>
							<small class="site-description">Enjoy your Life</small>
						</div>
					</a> <!-- #branding -->
					<div class="main-navigation">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item <%=current_item_link root_path%>"><a href="">Home</a></li>
							<li class="menu-item <%=current_item_link reviews_path%>"><%=link_to t("application.reviews"),reviews_path%></li>
							<% if !current_user %>
							<li class="menu-item <%=current_item_link new_user_registration_path%>"><%=link_to t("application.sign_up"),new_user_registration_path%></li>
							<li class="menu-item <%=current_item_link new_user_session_path%>"><%=link_to t("application.login"),new_user_session_path%></li>
							<% else %>
							<% if current_user.is_admin %>
							<li class="menu-item">
								<ul class="menu">
							      <li class="dropdown">
								       <a class="dropdown-toggle"
								           data-toggle="dropdown"
								           href="#">
								            Admin manager
								            <b class="caret"></b>
								        </a>
								        <ul class="dropdown-menu">
								          <li class="menu-item <%=current_item_link admin_users_path%>"><%=link_to t("Manager_users"),admin_users_path%></li>
										  <li class="menu-item <%=current_item_link admin_reviews_path%>"><%=link_to t("Manager_reviews"),admin_reviews_path%></li>
										  <li class="menu-item <%=current_item_link admin_categories_path%>"><%=link_to t("Manager_categoty"),admin_categories_path%></li>
								        </ul>
      								</li>
    							</ul>
							</li>
							<%end%>
							<li class="menu-item <%=current_item_link new_review_path%>"><%=link_to t("application.new_review"),new_review_path%></li>
							<li class="menu-item <%=current_item_link profile_path%>"><%=link_to t("application.profile"),profile_path%></li>
							<li class="menu-item <%=current_item_link destroy_user_session_url%>"><%=link_to t("application.logout"),destroy_user_session_url, method: :delete%></li>
							<% end %>
						</ul> <!-- .menu -->
						
						<%= form_tag(reviews_path, :method => "get", class: "search-form") do %>
							<%= text_field_tag :search, params[:search], placeholder: "Search review" %>
							<button><i class="fa fa-search"></i></button>
							<div class="" style="height: 38px;position: absolute;width: 35px;top: 50px;z-index: 10000;cursor: pointer;"></div>
						<% end %>
						
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header>
			<main class="main-content">
				<div class="container">
					<div class="page">
					<% flash.each do |name, msg| %>
  					<% if msg.is_a?(String) %>
    					<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      					<%= content_tag :div, msg, :id => "flash_#{name}" %>
    					</div>
  					<% end %>
					<% end %>
					<%= yield %>
					</div>
				</div>
			</main>
			<footer class="site-footer">


					<div class="colophon">Copyright 2014 RocketTeam, Designed by BigBugTeam. All rights reserved</div>
				</div> <!-- .container -->

			</footer>
		</div>
  </body>
</html>